collections:
  - name: google.cloud

roles:
  - src: https://github.com/opsta/ansible-gcp-instance.git
    version: "main"
    name: gcp_instance
  - src: https://github.com/opsta/ansible-mongodb.git
    version: "master"
    name: mongodb
